"""initial FailureLens schema

Revision ID: 2bdd16d7c241
Revises:
Create Date: 2026-09-26 21:18:44.439867
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2bdd16d7c241"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "partial",
                "failed",
                "cancelled",
                "dead_lettered",
                name="jobstate",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=240), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_claim", "jobs", ["state", "available_at"], unique=False)
    op.create_index(op.f("ix_jobs_project_id"), "jobs", ["project_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=240), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("repository", sa.String(length=240), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("base_sha", sa.String(length=64), nullable=True),
        sa.Column("branch", sa.String(length=240), nullable=True),
        sa.Column("framework", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "processing",
                "complete",
                "partial",
                "failed",
                name="runstatus",
            ),
            nullable=False,
        ),
        sa.Column("completeness", sa.String(length=32), nullable=False),
        sa.Column("expected_inputs", sa.Integer(), nullable=True),
        sa.Column("received_inputs", sa.Integer(), nullable=False),
        sa.Column("manifest_digest", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "external_id",
            "attempt",
            "manifest_digest",
            name="uq_run_identity",
        ),
    )
    op.create_index(op.f("ix_runs_project_id"), "runs", ["project_id"], unique=False)
    op.create_index(
        "ix_runs_project_started", "runs", ["project_id", "started_at"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("original_name", sa.String(length=1024), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("safe_storage_path", sa.String(length=2048), nullable=False),
        sa.Column("media_type", sa.String(length=160), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("redaction_version", sa.String(length=40), nullable=False),
        sa.Column("restricted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "digest", "kind", name="uq_artifact_run_digest_kind"
        ),
    )
    op.create_index(op.f("ix_artifacts_run_id"), "artifacts", ["run_id"], unique=False)
    op.create_table(
        "test_executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("test_identity", sa.String(length=512), nullable=False),
        sa.Column("suite", sa.String(length=512), nullable=True),
        sa.Column("source_path", sa.String(length=1024), nullable=True),
        sa.Column("parameterization", sa.String(length=512), nullable=True),
        sa.Column("browser", sa.String(length=80), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "passed", "failed", "skipped", "cancelled", "unknown", name="outcome"
            ),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("retry_recovered", sa.Boolean(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_execution_identity",
        "test_executions",
        ["run_id", "test_identity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_executions_run_id"), "test_executions", ["run_id"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("locator", sa.JSON(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_artifact_id"), "evidence", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_project_id"), "evidence", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_run_id"), "evidence", ["run_id"], unique=False)
    op.create_table(
        "failures",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("exception_type", sa.String(length=240), nullable=True),
        sa.Column("strict_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("loose_features", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["test_executions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id"),
    )
    op.create_index(
        "ix_failure_fingerprint",
        "failures",
        ["project_id", "strict_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_failures_project_id"), "failures", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_failures_run_id"), "failures", ["run_id"], unique=False)
    op.create_table(
        "analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("failure_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "product_defect",
                "test_defect",
                "infrastructure_failure",
                "known_flake",
                "insufficient_evidence",
                name="category",
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("confidence_value", sa.Float(), nullable=True),
        sa.Column("confidence_kind", sa.String(length=40), nullable=False),
        sa.Column("confidence_explanation", sa.Text(), nullable=False),
        sa.Column("evidence_completeness", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("claims", sa.JSON(), nullable=False),
        sa.Column("supporting_evidence_ids", sa.JSON(), nullable=False),
        sa.Column("contradictory_evidence_ids", sa.JSON(), nullable=False),
        sa.Column("missing_evidence", sa.JSON(), nullable=False),
        sa.Column("hypotheses", sa.JSON(), nullable=False),
        sa.Column("next_investigation", sa.JSON(), nullable=False),
        sa.Column("abstention_reason", sa.Text(), nullable=True),
        sa.Column("policy_flags", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["failure_id"], ["failures.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("failure_id", "revision", name="uq_analysis_revision"),
    )
    op.create_index(
        op.f("ix_analyses_failure_id"), "analyses", ["failure_id"], unique=False
    )
    op.create_table(
        "review_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=240), nullable=False),
        sa.Column("decision", sa.String(length=80), nullable=False),
        sa.Column("proposed_category", sa.String(length=80), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_events_analysis_id"),
        "review_events",
        ["analysis_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_events_analysis_id"), table_name="review_events")
    op.drop_table("review_events")
    op.drop_index(op.f("ix_analyses_failure_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_failures_run_id"), table_name="failures")
    op.drop_index(op.f("ix_failures_project_id"), table_name="failures")
    op.drop_index("ix_failure_fingerprint", table_name="failures")
    op.drop_table("failures")
    op.drop_index(op.f("ix_evidence_run_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_project_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_artifact_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_test_executions_run_id"), table_name="test_executions")
    op.drop_index("ix_execution_identity", table_name="test_executions")
    op.drop_table("test_executions")
    op.drop_index(op.f("ix_artifacts_run_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index("ix_runs_project_started", table_name="runs")
    op.drop_index(op.f("ix_runs_project_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_jobs_project_id"), table_name="jobs")
    op.drop_index("ix_jobs_claim", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
